/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Joel Anderson (https://sketchfab.com/joel3d)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/tyrannosarus-rex-free-model-e18c433cdd1c49f8ac152348b7384037
title: Tyrannosarus rex (Free model)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/dino/dino.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_4.geometry} material={materials.SkinColor} />
          <mesh geometry={nodes.Object_5.geometry} material={materials.eyeColor} />
          <mesh geometry={nodes.Object_6.geometry} material={materials.blackMatteColor} />
          <mesh geometry={nodes.Object_7.geometry} material={materials.eyeTransparentColor} />
          <mesh geometry={nodes.Object_8.geometry} material={materials.eyeTransparentColor} />
          <mesh geometry={nodes.Object_9.geometry} material={materials.eyeColor} />
          <mesh geometry={nodes.Object_10.geometry} material={materials.blackMatteColor} />
          <mesh geometry={nodes.Object_11.geometry} material={materials.teethTexture} />
          <mesh geometry={nodes.Object_12.geometry} material={materials.clawColor} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/dino.gltf')
