/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/pony.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[-293.27, 1527.86, -332.79]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Cylinder004.geometry} material={materials.shoxi} position={[17.09, 1411.69, -242.22]} rotation={[0, 0, Math.PI / 2]} />
        <mesh geometry={nodes.Detail016.geometry} material={materials.yollari} position={[17.09, 1411.69, -242.22]} rotation={[0, 0, Math.PI / 2]} />
        <mesh geometry={nodes.Sphere003.geometry} material={materials.dumi} position={[17.09, 1411.69, -242.22]} rotation={[0, 0, Math.PI / 2]} />
        <mesh geometry={nodes.Torus003.geometry} material={materials.qulogi} position={[17.09, 1411.69, -242.22]} rotation={[0, 0, Math.PI / 2]} />
        <mesh geometry={nodes.Torus004.geometry} material={materials.qulogi} position={[17.09, 1411.69, -242.22]} rotation={[0, 0, Math.PI / 2]} />
        <mesh geometry={nodes.Capsule005.geometry} material={materials.body} position={[17.09, 1411.69, -242.22]} rotation={[0, 0, Math.PI / 2]} />
      </group>
    </group>
  )
}

useGLTF.preload('/pony.gltf')
